# Generated by Django 5.1.4 on 2025-01-19 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0002_business_businessimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='Business.user'),
            preserve_default=False,
        ),
    ]
