# Generated by Django 5.1.4 on 2025-02-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0003_business_owner'),
        ('user', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_businesses', to='user.customuser'),
        ),
    ]
