# Generated by Django 5.1.4 on 2025-03-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0005_visiteduser'),
        ('user', '0003_customuser_phone_number_customuser_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitedUser',
            new_name='Visitor',
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='visited_at',
            new_name='visit_time',
        ),
        migrations.AlterUniqueTogether(
            name='visitor',
            unique_together={('business', 'user')},
        ),
    ]
