# Generated by Django 5.1.4 on 2025-03-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0006_rename_visiteduser_visitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='hours_of_operation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
