# Generated by Django 5.1.4 on 2026-01-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0010_business_landmark_socialmedialink_operatinghour'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='proof_of_business',
            field=models.FileField(blank=True, null=True, upload_to='proof/'),
        ),
    ]
