# Generated by Django 5.1.4 on 2026-04-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0017_remove_user_password_user_otp_user_otp_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='user',
            name='otp_expiry',
        ),
    ]
