# Generated by Django 5.1.4 on 2026-04-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0018_remove_user_otp_remove_user_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='Phone Verified'),
        ),
    ]
