# Generated by Django 5.1.4 on 2025-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Business', '0008_review'),
        ('user', '0003_customuser_phone_number_customuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_businesses',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='Business.business'),
        ),
    ]
