# Generated by Django 5.1.4 on 2026-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_customuser_saved_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
