# Generated by Django 5.1.4 on 2026-04-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_customuser_password_customuser_otp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_expiry',
        ),
    ]
